-- Battoo Intelligence
-- Migration 014: RAG context builder
--
-- Turns hybrid retrieval results into a structured, workspace-scoped context
-- suitable for an LLM. Knowledge and memory are kept explicitly separated,
-- ranked, and traceable to their source records.

CREATE TABLE IF NOT EXISTS ai_rag_contexts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    workspace_id UUID NOT NULL
        REFERENCES ai_workspaces(id)
        ON DELETE CASCADE,

    user_id UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,

    query_text TEXT NOT NULL,

    context JSONB NOT NULL DEFAULT '{}'::jsonb,

    knowledge_count INTEGER NOT NULL DEFAULT 0,
    memory_count INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_rag_contexts_workspace_created
ON ai_rag_contexts(workspace_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_rag_contexts_user_created
ON ai_rag_contexts(workspace_id, user_id, created_at DESC);

ALTER TABLE ai_rag_contexts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ai_rag_contexts_workspace_isolation
ON ai_rag_contexts;

CREATE POLICY ai_rag_contexts_workspace_isolation
ON ai_rag_contexts
FOR SELECT
TO authenticated
USING (is_workspace_member(workspace_id));

-- Build a structured RAG context without calling an LLM.
-- The application supplies the query embedding generated by its embedding model.
CREATE OR REPLACE FUNCTION build_rag_context(
    p_workspace_id UUID,
    p_query_text TEXT,
    p_query_embedding vector(1536),
    p_knowledge_limit INTEGER DEFAULT 8,
    p_memory_limit INTEGER DEFAULT 5,
    p_min_score DOUBLE PRECISION DEFAULT 0.20,
    p_vector_weight DOUBLE PRECISION DEFAULT 0.70,
    p_text_weight DOUBLE PRECISION DEFAULT 0.30,
    p_memory_type TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
    v_knowledge JSONB;
    v_memories JSONB;
    v_knowledge_count INTEGER;
    v_memory_count INTEGER;
BEGIN
    IF NOT is_workspace_member(p_workspace_id) THEN
        RAISE EXCEPTION 'workspace access denied';
    END IF;

    IF NULLIF(BTRIM(p_query_text), '') IS NULL THEN
        RAISE EXCEPTION 'query text is required';
    END IF;

    IF p_query_embedding IS NULL THEN
        RAISE EXCEPTION 'query embedding is required';
    END IF;

    SELECT
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'chunk_id', r.chunk_id,
                'content', r.content,
                'score', ROUND(r.hybrid_score::numeric, 6),
                'vector_score', ROUND(r.vector_score::numeric, 6),
                'text_score', ROUND(r.text_score::numeric, 6),
                'source', jsonb_build_object(
                    'document_id', d.id,
                    'title', d.title,
                    'file_name', d.original_file_name,
                    'document_type', d.document_type,
                    'source_id', s.id,
                    'source_type', s.source_type,
                    'source_name', s.source_name
                )
            ) ORDER BY r.hybrid_score DESC
        ), '[]'::jsonb),
        COUNT(*)::INTEGER
    INTO v_knowledge, v_knowledge_count
    FROM hybrid_knowledge_search(
        p_workspace_id,
        p_query_text,
        p_query_embedding,
        LEAST(GREATEST(p_knowledge_limit, 1), 50),
        p_min_score,
        p_vector_weight,
        p_text_weight
    ) r
    INNER JOIN knowledge_chunks kc
        ON kc.id = r.chunk_id
       AND kc.workspace_id = r.workspace_id
    LEFT JOIN knowledge_documents d
        ON d.id = kc.document_id
       AND d.workspace_id = kc.workspace_id
    LEFT JOIN knowledge_sources s
        ON s.id = d.source_id
       AND s.workspace_id = d.workspace_id;

    SELECT
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'memory_id', r.memory_id,
                'memory_type', r.memory_type,
                'content', r.content,
                'score', ROUND(r.hybrid_score::numeric, 6),
                'vector_score', ROUND(r.vector_score::numeric, 6),
                'text_score', ROUND(r.text_score::numeric, 6),
                'importance', m.importance,
                'confidence', m.confidence,
                'source', m.source,
                'metadata', r.metadata
            ) ORDER BY r.hybrid_score DESC, m.importance DESC
        ), '[]'::jsonb),
        COUNT(*)::INTEGER
    INTO v_memories, v_memory_count
    FROM hybrid_memory_search(
        p_workspace_id,
        p_query_text,
        p_query_embedding,
        LEAST(GREATEST(p_memory_limit, 1), 50),
        p_min_score,
        0.75,
        0.25,
        p_memory_type
    ) r
    INNER JOIN ai_memory_entries m
        ON m.id = r.memory_id
       AND m.workspace_id = r.workspace_id;

    RETURN jsonb_build_object(
        'version', '1.0',
        'workspace_id', p_workspace_id,
        'query', p_query_text,
        'knowledge', v_knowledge,
        'memories', v_memories,
        'counts', jsonb_build_object(
            'knowledge', v_knowledge_count,
            'memories', v_memory_count
        ),
        'retrieval', jsonb_build_object(
            'knowledge_vector_weight', p_vector_weight,
            'knowledge_text_weight', p_text_weight,
            'memory_vector_weight', 0.75,
            'memory_text_weight', 0.25,
            'min_score', p_min_score
        ),
        'generated_at', NOW()
    );
END;
$$;

REVOKE ALL ON FUNCTION build_rag_context(UUID, TEXT, vector(1536), INTEGER, INTEGER, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION build_rag_context(UUID, TEXT, vector(1536), INTEGER, INTEGER, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT) TO authenticated;

-- Persist a generated context for audit/debugging and later LLM orchestration.
CREATE OR REPLACE FUNCTION save_rag_context(
    p_workspace_id UUID,
    p_query_text TEXT,
    p_context JSONB
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_id UUID;
    v_knowledge_count INTEGER;
    v_memory_count INTEGER;
BEGIN
    IF NOT is_workspace_member(p_workspace_id) THEN
        RAISE EXCEPTION 'workspace access denied';
    END IF;

    v_knowledge_count := COALESCE((p_context->'counts'->>'knowledge')::INTEGER, 0);
    v_memory_count := COALESCE((p_context->'counts'->>'memories')::INTEGER, 0);

    INSERT INTO ai_rag_contexts (
        workspace_id,
        user_id,
        query_text,
        context,
        knowledge_count,
        memory_count
    )
    VALUES (
        p_workspace_id,
        auth.uid(),
        p_query_text,
        COALESCE(p_context, '{}'::jsonb),
        v_knowledge_count,
        v_memory_count
    )
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION save_rag_context(UUID, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION save_rag_context(UUID, TEXT, JSONB) TO authenticated;

-- Optional application-level formatter: produces a compact text context that
-- can be inserted into an LLM prompt while preserving source labels.
CREATE OR REPLACE FUNCTION format_rag_context(
    p_context JSONB,
    p_max_chars INTEGER DEFAULT 24000
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    v_text TEXT := '';
    r JSONB;
BEGIN
    v_text := v_text || '=== KNOWLEDGE ===' || E'\n';

    FOR r IN SELECT value FROM jsonb_array_elements(COALESCE(p_context->'knowledge', '[]'::jsonb)) LOOP
        v_text := v_text ||
            '[SOURCE: ' || COALESCE(r->'source'->>'title', r->'source'->>'file_name', 'unknown') || ']' || E'\n' ||
            '[SCORE: ' || COALESCE(r->>'score', '0') || ']' || E'\n' ||
            COALESCE(r->>'content', '') || E'\n\n';
    END LOOP;

    v_text := v_text || '=== MEMORY ===' || E'\n';

    FOR r IN SELECT value FROM jsonb_array_elements(COALESCE(p_context->'memories', '[]'::jsonb)) LOOP
        v_text := v_text ||
            '[MEMORY TYPE: ' || COALESCE(r->>'memory_type', 'unknown') || ']' || E'\n' ||
            '[CONFIDENCE: ' || COALESCE(r->>'confidence', '0') || ']' || E'\n' ||
            COALESCE(r->>'content', '') || E'\n\n';
    END LOOP;

    RETURN LEFT(v_text, LEAST(GREATEST(p_max_chars, 1000), 100000));
END;
$$;

REVOKE ALL ON FUNCTION format_rag_context(JSONB, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION format_rag_context(JSONB, INTEGER) TO authenticated;
